module KubernetesReferences
  class Pod < KubernetesReferences::API
    attr_accessor api_version: String
    attr_accessor kind: String
    attr_accessor metadata: ObjectMeta
    attr_accessor spec: PodSpec
    attr_accessor status: PodStatus

    def initialize: (untyped obj) -> void
  end
end
