module KubernetesReferences
  class PodCondition < KubernetesReferences::API
    attr_accessor last_probe_time: Time
    attr_accessor last_transition_time: Time
    attr_accessor message: String
    attr_accessor reason: String
    attr_accessor status: String
    attr_accessor type: String

    def initialize: (untyped obj) -> void
  end
end
