class KubernetesReferences::Lifecycle < KubernetesReferences::API
  attr_accessor post_start: ::KubernetesReferences::LifecycleHandler
  attr_accessor pre_stop: ::KubernetesReferences::LifecycleHandler

  def initialize: (untyped obj) -> void
end
