module KubernetesReferences
  class Lifecycle < KubernetesReferences::API
    attr_accessor post_start: LifecycleHandler
    attr_accessor pre_stop: LifecycleHandler

    def initialize: (untyped obj) -> void
  end
end
