module KubernetesReferences
  class PersistentVolumeClaimTemplate < KubernetesReferences::API
    attr_accessor metadata: ObjectMeta
    attr_accessor spec: PersistentVolumeClaimSpec

    def initialize: (untyped obj) -> void
  end
end