module KubernetesReferences
  class PersistentVolumeClaimVolumeSource < KubernetesReferences::API
    attr_accessor claim_name: String
    attr_accessor read_only: bool

    def initialize: (untyped obj) -> void
  end
end