module KubernetesReferences
  class ProjectedVolumeSource < KubernetesReferences::API
    attr_accessor default_mode: Integer
    attr_accessor sources: Array[VolumeProjection]

    def initialize: (untyped obj) -> void
  end
end