class KubernetesReferences::SELinuxOptions < KubernetesReferences::API
  attr_accessor level: String
  attr_accessor role: String
  attr_accessor type: String
  attr_accessor user: String

  def initialize: (untyped obj) -> void
end
