module KubernetesReferences
  class ServiceAccountTokenProjection < KubernetesReferences::API
    attr_accessor audience: String
    attr_accessor expiration_seconds: Integer
    attr_accessor path: String

    def initialize: (untyped obj) -> void
  end
end