module KubernetesReferences
  class RollingUpdateDeployment < KubernetesReferences::API
    attr_accessor max_surge: Integer
    attr_accessor max_unavailable: Integer

    def initialize: (untyped obj) -> void
  end
end
