module KubernetesReferences
  class CinderVolumeSource < KubernetesReferences::API
    attr_accessor fs_type: String
    attr_accessor read_only: bool
    attr_accessor secret_ref: LocalObjectReference
    attr_accessor volume_id: String

    def initialize: (untyped obj) -> void
  end
end