module KubernetesReferences
  class QuobyteVolumeSource < KubernetesReferences::API
    attr_accessor group: String
    attr_accessor read_only: bool
    attr_accessor registry: String
    attr_accessor tenant: String
    attr_accessor user: String
    attr_accessor volume: String

    def initialize: (untyped obj) -> void
  end
end
