module KubernetesReferences
  class SecretVolumeSource < KubernetesReferences::API
    attr_accessor default_mode: Integer
    attr_accessor items: Array[KeyToPath]
    attr_accessor optional: bool
    attr_accessor secret_name: String

    def initialize: (untyped obj) -> void
  end
end