module KubernetesReferences
  class VsphereVirtualDiskVolumeSource < KubernetesReferences::API
    attr_accessor fs_type: String
    attr_accessor storage_policy_id: String
    attr_accessor storage_policy_name: String
    attr_accessor volume_path: String

    def initialize: (untyped obj) -> void
  end
end
